"""Write docs/SAMPLES.md: real sample conversations for the README (PHASE4 T5, plan section 10.5).

Each one is a real transaction replayed from its recording (tests/fixtures), answered by the configured model through
the same path as `explain` and the API (service.answer_transaction: triage, writer, answer check). Nothing in the
output is edited by hand.

Usage: uv run python scripts/sample_conversations.py
"""
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from anychain.config import load_config  # noqa: E402
from anychain.service import WRITE, answer_transaction  # noqa: E402
from anychain.writer import write_checked  # noqa: E402
from tests.conftest import replay_bundle  # noqa: E402
from tests.test_golden import _case  # noqa: E402

SAMPLES = [
    ("A successful ERC-20 transfer, support mode", "eth_usdc_transfer", "support", None, None),
    ("A failure diagnosed with reads on the node (eth_call), developer mode", "celo_fail_balance_confirmed",
     "developer", None, None),
    ("A failure diagnosed from the contract's verified code and the rule's repository source, with the sender's "
     "timeline, developer mode", "eth_fail_expired_v2", "developer", None, None),
    ("A contract the explorer has not verified (degradation), with a clarifying question (triage)",
     "eth_failed_unverified_bot", "support", None, ("intent", "other")),
    ("Triage: it succeeded, but the reader says the payment did not arrive", "eth_usdc_transfer", "support",
     "não recebi o pagamento", ("expected_receipt", "0x000000000000000000000000000000000000dEaD")),
    ("The private demo network: a BRLC call decoded from the configured repository, and the cause the explorer did "
     "not give recovered by replaying the call on the node, developer mode", "devnet_fail_access", "developer", None,
     None),
]


def _sources(text: str, bundle) -> list[str]:
    """Each fact the answer cites, with its sources: what a reader opens to check a citation."""
    import re
    cited = sorted({int(n) for n in re.findall(r"E(\d+)", text or "")})
    by_id = {e.id: e for e in bundle.items}
    out = []
    for n in cited:
        e = by_id.get(f"E{n}")
        if e is None:
            continue
        links = [f"[{s.label}]({s.url})" if s.url else s.label for s in e.sources]
        out.append(f"- **E{n}** ({e.kind}): " + ", ".join(links))
    return out


def run(fixture: str, mode: str, question, clarified=None):
    config, tx = _case(fixture)
    cfg = load_config(str(ROOT / "configs" / f"{config}.yaml"))
    return answer_transaction(tx, cfg, mode, write=WRITE, fresh=True, source="sample", log=None, store=None,
                              build=lambda h, c: replay_bundle(c, h, fixture), write_fn=write_checked,
                              finality=lambda: None, record=lambda log, e: None, question=question,
                              clarified=clarified), cfg, tx


def _why(why: str) -> str:
    """A source the recording has no answer for is replayed as unavailable; say that, not the replay's message."""
    if "no fixture for" in why:
        return "the recording has no answer from this source, so the replay treats it as unavailable"
    return why[:200]


def main() -> None:
    out = ["# Sample conversations", "",
           f"Generated by `scripts/sample_conversations.py` on {time.strftime('%Y-%m-%d')}: real transactions replayed "
           "from their recordings, answered by the configured model through the same path as `explain` and the API "
           "(triage, writer, answer check). Not edited by hand. Each `[E#]` is a numbered fact; the full evidence of "
           "each is printed by `anychain explain <hash> --evidence`.", ""]
    for title, fixture, mode, question, answer in SAMPLES:
        first, cfg, tx = run(fixture, mode, question)
        out += [f"## {title}", "", f"Network `{cfg.network.name}`, transaction `{tx}`, mode `{mode}`.", ""]
        if question:
            out += [f"**Reader:** {question}", ""]
        result = first
        if first.clarify is not None:
            c = first.clarify
            out += [f"**Assistant asks:** {c.question}", ""] + [f"- {o.label}" for o in c.options] + [""]
            if answer:
                kind, value = answer
                shown = next((o.label for o in c.options if o.id == value), value)
                out += [f"**Reader answers:** {shown}", ""]
                result, _cfg, _tx = run(fixture, mode, question, {"kind": kind, "answer": value})
        out += ["**Assistant:**", "", result.text or f"_(no written answer: {result.summary_status})_", ""]
        sources = _sources(result.text, result.bundle)
        if sources:
            out += ["<details><summary>Sources of the facts it cites</summary>", ""] + sources + ["", "</details>", ""]
        if result.bundle.gaps:
            out += ["**Missing data the answer declares:**", ""] + [f"- {g.what}: {_why(g.why)}" for g in result.bundle.gaps] + [""]
        print(f"{fixture}: {result.summary_status}", file=sys.stderr)
    (ROOT / "docs" / "SAMPLES.md").write_text("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
